In [1]:
import numpy as np
import pandas as pd

In [2]:
A= np.random.randint(1,100,200)
A.shape

(200,)

In [3]:
B=np.random.randint(2,40,200)
B.shape

(200,)

In [9]:
df=pd.DataFrame({1:A})
df2= pd.DataFrame({2:B})
df.head()

1
0  59
1  36
2  65
3  25
4  53

In [ ]:
df2.head()

0
0  11
1  20
2   9
3   8
4  29

In [10]:
df=pd.concat([df,df2],axis=1)
df.head()

1   2
0  59  11
1  36  15
2  65  20
3  25  20
4  53   4

In [24]:
new= df.cov()
arr=np.asarray(df)
print(np.cov(arr))

[[1152.   504.  1080.  ... 1872.  2016.  -288. ]
 [ 504.   220.5  472.5 ...  819.   882.  -126. ]
 [1080.   472.5 1012.5 ... 1755.  1890.  -270. ]
 ...
 [1872.   819.  1755.  ... 3042.  3276.  -468. ]
 [2016.   882.  1890.  ... 3276.  3528.  -504. ]
 [-288.  -126.  -270.  ... -468.  -504.    72. ]]


In [ ]:
X=df.iloc[:,0]
Y=df.iloc[:,1]

In [ ]:
import sklearn as sk

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()
X_scaled = sc.fit_transform(pd.DataFrame(X))


In [ ]:
type(X_scaled)

numpy.ndarray

In [ ]:
A1 = np.ones(X_scaled.shape[0])
A1=A1.reshape(len(A1),1)

In [ ]:
X_scaled= np.concatenate([A1,X_scaled],axis=1)

In [ ]:
X_scaled.shape

(200, 2)

In [ ]:
# formula beta = (X*X.T).inv * X.T * Y

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled,Y.values,test_size=0.30,random_state=42)

In [ ]:
A = X_train.T.dot(X_train) 

In [ ]:
B= np.linalg.inv(A)

In [ ]:
C = B.dot(X_train.T)

In [ ]:
beta= C.dot(Y_train)

In [ ]:
beta

array([20.82348212,  0.20336533])

In [ ]:
predicted = X_test.dot(beta) 

In [ ]:
predicted

array([20.85455964, 20.75836732, 21.03214547, 21.12093838, 20.89155669,
       20.45499154, 20.97295019, 21.14313661, 21.09134074, 20.9803496 ,
       20.70657146, 20.54378445, 20.8989561 , 20.59558031, 20.72876968,
       20.92855374, 20.67697382, 21.06914251, 20.92115433, 20.8989561 ,
       20.75096791, 21.03214547, 20.8175626 , 20.48458917, 20.86935846,
       21.15793543, 20.95075196, 20.75836732, 20.72876968, 20.46979036,
       20.63997677, 20.61037913, 20.53638504, 20.95815137, 20.49198858,
       21.0617431 , 20.75836732, 20.61777854, 21.04694429, 21.17273425,
       20.80276378, 21.01734665, 20.56598268, 21.08394133, 20.64737618,
       20.88415728, 20.79536437, 20.56598268, 20.77316614, 21.11353897,
       20.68437323, 20.72137027, 21.03214547, 21.15053602, 21.00254783,
       20.98774901, 21.09134074, 21.16533484, 20.54378445, 20.88415728])

In [ ]:
from sklearn import metrics

In [ ]:
metrics.r2_score(predicted,Y_test)

-2619.44635270255

In [ ]:
#beta with ridge regression
lamba =0.0001
A= X_train.T.dot(X_train)
A1 = np.identity( A.shape[0])
A= np.add(A,lamba*A1)
B= np.linalg.inv(A)
C= B.dot(X_train.T)
beta2 = C.dot(Y_train)



In [ ]:
beta2

array([20.82346721,  0.20336449])

In [ ]:
predicted_2 = X_test.dot(beta2)
metrics.r2_score(predicted_2,Y_test)

-2619.467406041621

In [ ]:
from sklearn.preprocessing import PolynomialFeatures


In [ ]:
pp= PolynomialFeatures(20)
X_new = pp.fit_transform(pd.DataFrame(X))

In [ ]:
tmp_dataf =pd.DataFrame(X_new)
new_frame = tmp_dataf.iloc[:,1:]

In [ ]:
sc=StandardScaler()
X_new = sc.fit_transform(pd.DataFrame(new_frame))

In [ ]:
X_new= np.concatenate([A1,X_new],axis=1)

In [ ]:
X_new

array([[ 1.        ,  1.20797575,  1.30846159, ...,  0.02369112,
        -0.01238851, -0.04350718],
       [ 1.        , -0.24741672, -0.49243662, ..., -0.32529673,
        -0.31535044, -0.30620506],
       [ 1.        , -1.26619145, -1.08335635, ..., -0.3252998 ,
        -0.31535184, -0.3062057 ],
       ...,
       [ 1.        ,  0.95328207,  0.91205294, ..., -0.25241784,
        -0.25735459, -0.26010724],
       [ 1.        ,  1.28074538,  1.42805248, ...,  0.20773934,
         0.1584036 ,  0.11436685],
       [ 1.        ,  0.4438947 ,  0.22264659, ..., -0.32333229,
        -0.31407082, -0.30537263]])

In [ ]:
lambd =1000
A= X_new.T.dot(X_new)
tmp2 = np.identity(A.shape[0])
A= np.add(A,lamba*tmp2)
B=np.linalg.inv(A)
C= B.dot(X_new.T)
beta3=C.dot(Y)

In [ ]:
beta3

array([  20.56998972,   -6.81686686,    9.40143847,  -22.44307069,
         -1.6383253 ,   63.7045498 ,   34.72003791,  -33.03625466,
        -74.75915594,  -67.72691586,  -22.18212816,   36.35796717,
         81.24142252,   93.71237239,   67.35438898,    9.04569974,
        -62.33246889, -118.34013611, -123.77311928,  -39.31119162,
        176.23012282])

In [ ]:
predicted_3 = X_new.dot(beta3)
metrics.r2_score(predicted_3,Y)

-30.974752688805975