In [1]:
!pip install nltk

In [2]:
import nltk
#nltk.download('brown')

In [5]:
from nltk.corpus import *

In [23]:
nltk.download('stopwords')
nltk.download('brown')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\91953\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package brown to
[nltk_data]     C:\Users\91953\AppData\Roaming\nltk_data...
[nltk_data]   Package brown is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\91953\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [7]:
nltk.corpus.stopwords.fileids()

['arabic',
 'azerbaijani',
 'danish',
 'dutch',
 'english',
 'finnish',
 'french',
 'german',
 'greek',
 'hungarian',
 'indonesian',
 'italian',
 'kazakh',
 'nepali',
 'norwegian',
 'portuguese',
 'romanian',
 'russian',
 'slovene',
 'spanish',
 'swedish',
 'tajik',
 'turkish']

In [11]:
nltk.corpus.brown.sents()[:100]

[['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', 'Friday', 'an', 'investigation', 'of', "Atlanta's", 'recent', 'primary', 'election', 'produced', '``', 'no', 'evidence', "''", 'that', 'any', 'irregularities', 'took', 'place', '.'], ['The', 'jury', 'further', 'said', 'in', 'term-end', 'presentments', 'that', 'the', 'City', 'Executive', 'Committee', ',', 'which', 'had', 'over-all', 'charge', 'of', 'the', 'election', ',', '``', 'deserves', 'the', 'praise', 'and', 'thanks', 'of', 'the', 'City', 'of', 'Atlanta', "''", 'for', 'the', 'manner', 'in', 'which', 'the', 'election', 'was', 'conducted', '.'], ...]

In [12]:
import os
filenames=os.listdir('C:/Users/91953/OneDrive/Desktop/dataset/')
content=[]
for i in range(len(filenames)):
    f=open('C:/Users/91953/OneDrive/Desktop/dataset/'+filenames[i],'r')
    text=f.read()
    content.append(text)
    f.close()
print(content)

['Hi, How are you?\n', "I'm practicing for Convo Exam."]


In [13]:
from nltk.corpus import PlaintextCorpusReader

In [27]:
a=PlaintextCorpusReader('C:/Users/91953/OneDrive/Desktop/dataset/','.*')

In [28]:
a.fileids()

['A.txt', 'B.txt']

In [29]:
a.words()

['Hi', ',', 'How', 'are', 'you', '?', 'I', "'", 'm', ...]

In [30]:
content1=[]
for i in range(len(a.fileids())):
    content1.append(''.join(a.raw(fileids=a.fileids()[i])))

In [31]:
print(content1)

["Hi, How are you? I'm too much good\r\n", "I'm practicing for Convo Exam."]


In [7]:
import os
content=[]
filenames=os.listdir('C:/Users/jasme/Desktop/dataset/')
for i in range(len(filenames)):
    f=open('C:/Users/jasme/Desktop/dataset/'+filenames[i])
    text=f.read()
    content.append(text)
    f.close()
print(content)

['Hi how are you. I am fine', 'I am studying Converastional AI']


In [34]:
import nltk
normalize=[]

for i in range(len(content1)):
    normalize.append(' '.join([word.lower() for word in content1[i].split() if word.isalpha()]))
print(normalize)

['how are too much good', 'practicing for convo']


In [20]:
from nltk import word_tokenize

In [35]:
tokenize=[]
for i in range(len(normalize)):
    tokenize.append(nltk.word_tokenize(normalize[i]))
print(tokenize)

[['how', 'are', 'too', 'much', 'good'], ['practicing', 'for', 'convo']]


In [25]:
import nltk
from nltk.corpus import *
stopword_list=nltk.corpus.stopwords.words(fileids='english')
print(stopword_list)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [36]:
nostop=[]
for i in range(len(tokenize)):
    nostop.append([word for word in tokenize[i] if word not in stopword_list])
print(nostop)

[['much', 'good'], ['practicing', 'convo']]


In [37]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()
final=[]
for i in range(len(nostop)):
    final.append(' '.join([ps.stem(word) for word in nostop[i]]))
print(final)

['much good', 'practic convo']


In [38]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
X=cv.fit_transform(final)
print(X.toarray())
print(cv.get_feature_names())

[[0 1 1 0]
 [1 0 0 1]]
['convo', 'good', 'much', 'practic']


In [42]:
import pandas as pd
bow=pd.DataFrame(data=X.toarray(),columns=cv.get_feature_names(),index=a.fileids())

In [43]:
print(bow)

       convo  good  much  practic
A.txt      0     1     1        0
B.txt      1     0     0        1


In [44]:
doc_count={}
for i in range(len(final)):
    word_count={}
    for word in final[i].split():
        if word not in word_count.keys():
            word_count[word]=0
        word_count[word]+=1
    doc_count[filenames[i]]=word_count
print(doc_count)

{'A.txt': {'much': 1, 'good': 1}, 'B.txt': {'practic': 1, 'convo': 1}}


In [45]:
bow1=pd.DataFrame(doc_count)

In [46]:
bow1

A.txt  B.txt
convo      NaN    1.0
good       1.0    NaN
much       1.0    NaN
practic    NaN    1.0

In [47]:
bow1.fillna(0,inplace=True)

In [22]:
bow1

a.txt  b.txt
hi           1.0    0.0
fine         1.0    0.0
studi        0.0    1.0
converast    0.0    1.0
ai           0.0    1.0

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer(norm=False,smooth_idf=False)
X1=tf.fit_transform(final)
print(X1.toarray())
print(tf.get_feature_names())

[[0.         1.69314718 1.69314718 0.        ]
 [1.69314718 0.         0.         1.69314718]]
['convo', 'good', 'much', 'practic']
