In [1]:
import pandas as pd
import numpy as np
import sklearn
import nltk

In [3]:
from nltk.corpus import PlaintextCorpusReader
a=PlaintextCorpusReader('./dataset/','.*')
print(a.fileids())

['A.txt', 'B.txt', 'C.txt', 'D.txt', 'E.txt']


In [6]:
content=[]
for i in range(len(a.fileids())):
  content.append(''.join( a.raw(a.fileids()[i])))

content

['Computer science is the study of algorithmic processes, computational machines and computation itself.[1] As a discipline, computer science spans a range of topics from theoretical studies of algorithms, computation and information to the practical issues of implementing computational systems in hardware and software.[2][3]\r\n\r\nIts fields can be divided into theoretical and practical disciplines. For example, the theory of computation concerns abstract models of computation and general classes of problems that can be solved using them, while computer graphics or computational geometry emphasize more specific applications. Algorithms and data structures have been called the heart of computer science.[4] Programming language theory considers approaches to the description of computational processes, while computer programming involves the use of them to create complex systems. Computer architecture describes construction of computer components and computer-operated equipment. Artific

In [9]:
normalized=[]

for i in range(len(content)):
  normalized.append(' '.join(word.lower() for word in content[i].split() if word.isalpha() ))
normalized

['computer science is the study of algorithmic computational machines and computation as a computer science spans a range of topics from theoretical studies of computation and information to the practical issues of implementing computational systems in hardware and its fields can be divided into theoretical and practical for the theory of computation concerns abstract models of computation and general classes of problems that can be solved using while computer graphics or computational geometry emphasize more specific algorithms and data structures have been called the heart of computer programming language theory considers approaches to the description of computational while computer programming involves the use of them to create complex computer architecture describes construction of computer components and artificial intelligence aims to synthesize processes such as environmental planning and learning found in humans and a digital computer is capable of simulating various informatio

In [11]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [12]:
tokenized=[]
from nltk import word_tokenize
for i in range(len(normalized)):
  tokenized.append(word_tokenize(normalized[i]))
tokenized

[['computer',
  'science',
  'is',
  'the',
  'study',
  'of',
  'algorithmic',
  'computational',
  'machines',
  'and',
  'computation',
  'as',
  'a',
  'computer',
  'science',
  'spans',
  'a',
  'range',
  'of',
  'topics',
  'from',
  'theoretical',
  'studies',
  'of',
  'computation',
  'and',
  'information',
  'to',
  'the',
  'practical',
  'issues',
  'of',
  'implementing',
  'computational',
  'systems',
  'in',
  'hardware',
  'and',
  'its',
  'fields',
  'can',
  'be',
  'divided',
  'into',
  'theoretical',
  'and',
  'practical',
  'for',
  'the',
  'theory',
  'of',
  'computation',
  'concerns',
  'abstract',
  'models',
  'of',
  'computation',
  'and',
  'general',
  'classes',
  'of',
  'problems',
  'that',
  'can',
  'be',
  'solved',
  'using',
  'while',
  'computer',
  'graphics',
  'or',
  'computational',
  'geometry',
  'emphasize',
  'more',
  'specific',
  'algorithms',
  'and',
  'data',
  'structures',
  'have',
  'been',
  'called',
  'the',
  'hea

In [14]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [16]:
from nltk.corpus import stopwords

stopword_list= stopwords.words(fileids='english')
stopword_list

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [19]:
filtered=[]
for i in range(len(tokenized)):
  filtered.append(' '.join( word for word in tokenized[i] if word not in stopword_list ))

filtered

['computer science study algorithmic computational machines computation computer science spans range topics theoretical studies computation information practical issues implementing computational systems hardware fields divided theoretical practical theory computation concerns abstract models computation general classes problems solved using computer graphics computational geometry emphasize specific algorithms data structures called heart computer programming language theory considers approaches description computational computer programming involves use create complex computer architecture describes construction computer components artificial intelligence aims synthesize processes environmental planning learning found humans digital computer capable simulating various information fundamental concern computer science determining computer scientists usually focus academic turing award generally recognized highest distinction computer',
 'earliest foundations would become computer scien

In [30]:
from nltk.stem import PorterStemmer

ps= PorterStemmer()
final=[]

for i in range(len(filtered)):
  final.append(' '.join([ps.stem(word) for word in filtered[i].split() ]))

final

['comput scienc studi algorithm comput machin comput comput scienc span rang topic theoret studi comput inform practic issu implement comput system hardwar field divid theoret practic theori comput concern abstract model comput gener class problem solv use comput graphic comput geometri emphas specif algorithm data structur call heart comput program languag theori consid approach descript comput comput program involv use creat complex comput architectur describ construct comput compon artifici intellig aim synthes process environment plan learn found human digit comput capabl simul variou inform fundament concern comput scienc determin comput scientist usual focu academ ture award gener recogn highest distinct comput',
 'earliest foundat would becom comput scienc predat invent modern digit machin calcul fix numer task abacu exist sinc aid comput multipl algorithm perform comput exist sinc even develop sophist comput wilhelm schickard design construct first work mechan calcul gottfri le

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer()
X_1=cv.fit_transform(final)
print(X_1.toarray())
print(cv.get_feature_names())

[[0 1 1 ... 0 0 0]
 [1 0 0 ... 1 1 0]
 [0 0 1 ... 0 0 1]
 [0 0 0 ... 1 0 0]
 [0 1 0 ... 1 0 0]]
['abacu', 'abstract', 'academ', 'achiev', 'ada', 'adopt', 'aid', 'aim', 'alan', 'algorithm', 'almost', 'alonzo', 'also', 'altern', 'although', 'amnon', 'among', 'amount', 'analog', 'analyst', 'analyt', 'anoth', 'appear', 'appli', 'approach', 'architectur', 'area', 'argu', 'around', 'articl', 'artifact', 'artifici', 'astronomi', 'attribut', 'automat', 'award', 'babbag', 'becom', 'bernoulli', 'binari', 'branch', 'busi', 'calcul', 'call', 'capabl', 'card', 'categori', 'certain', 'certainli', 'characterist', 'charl', 'church', 'claim', 'class', 'closer', 'cognit', 'colmar', 'commerci', 'commun', 'complementari', 'complex', 'compon', 'comptologist', 'comput', 'concern', 'consid', 'construct', 'contenti', 'context', 'continu', 'contract', 'creat', 'creation', 'crucial', 'cue', 'daili', 'danish', 'data', 'datalog', 'david', 'day', 'de', 'deduct', 'demonstr', 'depart', 'deploy', 'deriv', 'describ', 

In [32]:
df1= pd.DataFrame(X_1.toarray(),columns=cv.get_feature_names(),index=a.fileids())

In [33]:
df1.head()

abacu  abstract  academ  achiev  ada  ...  wilhelm  word  work  would  year
A.txt      0         1       1       0    0  ...        0     0     0      0     0
B.txt      1         0       0       0    1  ...        1     0     1      1     0
C.txt      0         0       1       0    0  ...        0     1     0      0     1
D.txt      0         0       0       1    0  ...        0     0     1      0     0
E.txt      0         1       0       0    0  ...        0     0     1      0     0

[5 rows x 305 columns]

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer
tt=TfidfVectorizer()
X_2= tt.fit_transform(final)
print(X_2.toarray())
print(tt.get_feature_names())
df2=pd.DataFrame(X_2.toarray(),columns=tt.get_feature_names(),index=a.fileids())
df2.head()

[[0.         0.06387686 0.06387686 ... 0.         0.         0.        ]
 [0.07279635 0.         0.         ... 0.04875256 0.07279635 0.        ]
 [0.         0.         0.04333374 ... 0.         0.         0.05371105]
 [0.         0.         0.         ... 0.06831282 0.         0.        ]
 [0.         0.11033696 0.         ... 0.09158964 0.         0.        ]]
['abacu', 'abstract', 'academ', 'achiev', 'ada', 'adopt', 'aid', 'aim', 'alan', 'algorithm', 'almost', 'alonzo', 'also', 'altern', 'although', 'amnon', 'among', 'amount', 'analog', 'analyst', 'analyt', 'anoth', 'appear', 'appli', 'approach', 'architectur', 'area', 'argu', 'around', 'articl', 'artifact', 'artifici', 'astronomi', 'attribut', 'automat', 'award', 'babbag', 'becom', 'bernoulli', 'binari', 'branch', 'busi', 'calcul', 'call', 'capabl', 'card', 'categori', 'certain', 'certainli', 'characterist', 'charl', 'church', 'claim', 'class', 'closer', 'cognit', 'colmar', 'commerci', 'commun', 'complementari', 'complex', 'compon

abacu  abstract    academ  ...      work     would      year
A.txt  0.000000  0.063877  0.063877  ...  0.000000  0.000000  0.000000
B.txt  0.072796  0.000000  0.000000  ...  0.048753  0.072796  0.000000
C.txt  0.000000  0.000000  0.043334  ...  0.000000  0.000000  0.053711
D.txt  0.000000  0.000000  0.000000  ...  0.068313  0.000000  0.000000
E.txt  0.000000  0.110337  0.000000  ...  0.091590  0.000000  0.000000

[5 rows x 305 columns]